<?php
/**
 * Created by PhpStorm.
 * User: Vesela.Ferdinandova
 * Date: 5/3/2018
 * Time: 1:59 PM
 */

namespace App\Tests\TravelAdvisor\Domain\Model;

use App\TravelAdvisor\Domain\Exceptions\MissingArgumentException;
use App\TravelAdvisor\Domain\Model\AirportCard;
use PHPUnit\Framework\TestCase;

class AirportCardTest extends TestCase
{
    /**
     * @var array
     */
    private $data;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->data = json_decode(file_get_contents(__DIR__ . '/data/unsorted_cards.json'));
    }

    /**
     * @throws MissingArgumentException
     */
    public function testCreationFromJson()
    {

        $boardingCard = AirportCard::createFromJson($this->data[3]);
        $this->assertInstanceOf(AirportCard::class, $boardingCard);
        $this->assertEquals('Sofia', $boardingCard->getStartDirection());
        $this->assertEquals('Plovdiv Aiport', $boardingCard->getEndDirection());
        $this->assertEquals('1C', $boardingCard->getSeatNumber());
        $this->assertEquals('12323BBB', $boardingCard->getCardNumber());
        $this->assertEquals('airport', $boardingCard->getTransportationType());
        $this->assertEquals('Get your luggage from Gate B11', $boardingCard->getLuggageInstructions());
        $this->assertEquals('1B', $boardingCard->getGate());
        $this->assertEquals(
            'From Sofia, take flight 12323BBB to Plovdiv Aiport. Gate 1B, seat 1C. Get your luggage from Gate B11',
            $boardingCard->getInstructions()
        );
    }

    /**
     * @expectedException \App\TravelAdvisor\Domain\Exceptions\MissingArgumentException
     */
    public function testCreationFromJsonWitWrongData()
    {
        AirportCard::createFromJson($this->data[0]);
    }
}