<?php
/**
 * Created by PhpStorm.
 * User: Vesela.Ferdinandova
 * Date: 5/3/2018
 * Time: 1:59 PM
 */

namespace App\Tests\TravelAdvisor\Domain\Model;

use App\TravelAdvisor\Domain\Exceptions\MissingArgumentException;
use App\TravelAdvisor\Domain\Model\AirportCard;
use App\TravelAdvisor\Domain\Model\TrainStationCard;
use PHPUnit\Framework\TestCase;

class TrainCardTest extends TestCase
{
    /**
     * @var array
     */
    private $data;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->data = json_decode(file_get_contents(__DIR__ . '/data/unsorted_cards.json'));
    }

    /**
     * @throws MissingArgumentException
     */
    public function testCreationFromJson()
    {

        $boardingCard = TrainStationCard::createFromJson($this->data[2]);
        $this->assertInstanceOf(TrainStationCard::class, $boardingCard);
        $this->assertEquals('Plovdiv Train Station', $boardingCard->getStartDirection());
        $this->assertEquals('Burgas', $boardingCard->getEndDirection());
        $this->assertEquals('1C', $boardingCard->getSeatNumber());
        $this->assertEquals('12WE', $boardingCard->getCardNumber());
        $this->assertEquals(
            'Take train 12WE, from Plovdiv Train Station to Burgas. Sit in seat 1C',
            $boardingCard->getInstructions()
        );
    }

    /**
     * @expectedException \App\TravelAdvisor\Domain\Exceptions\MissingArgumentException
     */
    public function testCreationFromJsonWitWrongData()
    {
        AirportCard::createFromJson($this->data[0]);
    }
}